### PR TITLE
add dart-services from gridaco/base

### PR DESCRIPTION
**Pull request by softmarshmallow**
Migration of dart-services api wrapper.

@tomoyuki28jp

Thank to PR
- https://github.com/gridaco/base/pull/44
- https://github.com/gridaco/base/pull/43

### CODE REVIEW

**Comment by softmarshmallow** [comment]
@tomoyuki28jp

New version with your contribution released to npm with version 0.2.6, 
Also I've added the "types" field to package.json which will hopefully fix the issue you've faced https://github.com/gridaco/base/pull/43#issuecomment-1423857717
https://www.npmjs.com/package/dart-services

**Comment by tomoyuki28jp** [comment]
@softmarshmallow When I run my app with `"dart-services": "^0.2.6"`, the following error occurred.

```
./node_modules/dart-services/dist/index.js:54:0
Module not found: Can't resolve 'axios'
```

**Comment by tomoyuki28jp** [comment]
`yarn add axios` resolve the error. (I think v0.2.5 didn't require the procedure though.)

**Comment by tomoyuki28jp** [comment]
I don't need to add myself as a contributor because I'm too lazy to do it :)

So please feel free to close this issue anytime that is convenient for you.

Thank you for your work!

**Comment by tomoyuki28jp** [comment]
After one night, my project start raining the following error somehow :(

```
Could not find a declaration file for module 'dart-services'. '/path/to/my-project/node_modules/dart-services/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/dart-services` if it exists or add a new declaration (.d.ts) file containing `declare module 'dart-services';`ts(7016)
```

`rm -rf node_modules & yarn` didn't solve the error.

There is only one file named `index.js` under the `node_modules/dart-services/dist/` dir.

**Comment by softmarshmallow** [comment]
@tomoyuki28jp 
Thank you for reporting. Must have missed that when i changed packager from tsc to tsup.
Will re pub the new version now. :)

**Comment by softmarshmallow** [comment]
Screenshot 2023-02-10 at 10 38 04 PM


0.2.7 with .d.ts

**Comment by tomoyuki28jp** [comment]
@softmarshmallow Confirmed that v0.2.7 is working fine! Thank you for your work.

**Pull request merged**
